services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: events
    ports: ["5432:5432"]
    volumes:
      - ./internal/db/migrations:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U app -d events"]
      interval: 2s
      timeout: 2s
      retries: 20
  api:
    build: .
    environment:
      DB_DSN: postgres://app:app@db:5432/events?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
    ports: ["8080:8080"]
