services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: events
    ports: ["5432:5432"]
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./internal/db/migrations/0001_init.sql:/docker-entrypoint-initdb.d/0001_init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d events"]
      interval: 5s
      timeout: 3s
      retries: 20

  api:
    build: .
    environment:
      DATABASE_URL: postgres://app:app@db:5432/events?sslmode=disable
    ports: ["8080:8080"]
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8080/health"]
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  db-data:
